### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by alexprice1** [supnate/memobind#1]
Hey, pretty cool idea. I'm pretty sure though, in the current form, this will introduce s memory leak.

**Comment by supnate** [comment]
Thank you @alexprice91 , would you please explain more about the issue?

**Comment by alexprice1** [comment]
I'm sorry. I just re-read your code. You are binding it against the component. Nevermind, you should be good :-)

**Comment by supnate** [comment]
No problem, thank you @alexprice91 .
